### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by M-ds** [M-ds/InssUtils#6]
Go through the whole flow of the project and clean the code as far as possible.

**TODO**
- [x] generators
- [x] validators
- [x] utils
- [x] make sure the project is loosely coupled
- [x] make sure small methods are used
- [x] as little complexity as possible
